### ISSUE TITLE
Add beautifulsoup4 to requirements.txt

### ISSUE THREAD

**Issue by Greelan** [yuyu1815/palworld-discord-bot#1]
The `beautifulsoup4` package is a requirement for `python_steam_api`: https://pypi.org/project/python-steam-api/

It should be added to requirements.txt.

**Comment by yuyu1815** [comment]
Also sorry for the late reply.
We will correct this as soon as possible.

**Comment by Greelan** [comment]
Thanks. Can you also update `requirements.txt` in the `code` directory?

**Comment by yuyu1815** [comment]
Sorry, I forgot.
